version: 2
jobs:
  install:
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: sh scripts/install.sh
      - persist_to_workspace:
          root: .
          paths:
            - docker-cache

  test:
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run: sh scripts/test.sh

  build-service:
    machine:
        enabled: true
        docker_layer_caching: true
    working_directory: /tmp/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: sh scripts/build-service.sh

  # build-image-and-deploy:
  #   docker:
  #     - image: docker:18.01.0-ce-git
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - attach_workspace:
  #         at: ~/repo
  #     - run: sh scripts/build-images.sh
  # deploy:
  #   docker:
  #     - image: docker:18.01.0-ce-git
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run: sh scripts/build-images.sh


workflows:
  version: 2
  install_test:
    jobs:
      - install
      - test:
          requires:
            - install
      # - build-service:
      #     requires:
      #       - install

      # - build-image-and-deploy:
      #     requires:
      #       - build-service
      #     filters:
      #       branches:
      #         only:
      #           - master # /feature-.*/

  build_deploy:
    jobs:
      - install
      - build-service:
          requires:
            - install
  #
      # - deploy:
      #     requires:
      #       - install
      #     filters:
      #       branches:
      #         only:
      #           - master # /feature-.*/
