# version: 2
# jobs:
#   install:
#     docker:
#       - image: docker:18.01.0-ce-git
#     working_directory: ~/repo
#     steps:
#       - checkout
#       - run:
#           name: Do all the things
#           command: |
#             rootDirectory=$(pwd)
#             cd packages/users-service
#             serviceName=$(pwd | sed 's#.*/##')
#             echo "[INSTALL] ${serviceName} microservice: packages dependencies"
#             docker build -f Dockerfile.dev -t ${serviceName} .
#

#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: sh scripts/install.sh
      - persist_to_workspace:
          root: .
          paths:
            - docker-cache

  test:
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run: sh scripts/test.sh
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - docker-cache

  build-service:
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - run: sh scripts/build-service.sh

  # build-image-and-deploy:
  #   docker:
  #     - image: docker:18.01.0-ce-git
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - attach_workspace:
  #         at: ~/repo
  #     - run: sh scripts/build-images.sh
  # deploy:
  #   docker:
  #     - image: docker:18.01.0-ce-git
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run: sh scripts/build-images.sh


workflows:
  version: 2
  install_test:
    jobs:
      - install
      - test:
          requires:
            - install
      - build-service:
          requires:
            - test

      # - build-image-and-deploy:
      #     requires:
      #       - build-service

  # build_deploy:
  #   jobs:
  #     - install
  #     - build-service:
  #         requires:
  #           - install
  #
      # - deploy:
      #     requires:
      #       - install
      #     filters:
      #       branches:
      #         only:
      #           - master # /feature-.*/
