
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: docker:18.01.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: sh scripts/install.sh
      - persist_to_workspace:
          root: ~/repo/docker-cache
          paths:
            - docker

  test:
    docker:
      - image: docker:18.01.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: ~/repo/docker-cache
      - run: sh scripts/test.sh

  # deploy:
  #   docker:
  #     - image: docker:18.01.0-ce-git
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run: sh scripts/build-images.sh


workflows:
  version: 2
  install_test:
    jobs:
      - install
      - test:
          requires:
            - install
      # - deploy:
      #     requires:
      #       - install
      #     filters:
      #       branches:
      #         only:
      #           - master # /feature-.*/
