
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo npm install -g lerna
      - run: lerna bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test
      # - run lerna run build:server
      - run: git config --global user.email "contact@nicolasfazio.ch"
      - run: git config --global user.name "FazioNico"
      - run: lerna publish --yes --skip-npm  --cd-version patch
      # - run: git merge
      # 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-job:
          filters:
            branch: dev # /feature-.*/
            commands:
              - git push master

      # - deploy-job:
      #     requires:
      #       - build-job
      #     filters:
      #       branches:
      #         only: master
